name: eventgate
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage:
  provider:
  dio:
  mobile_scanner:
  lucide_icons_flutter:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  android: false
  image_path: "assets/icon/app_icon_light.png"
  image_path_ios_dark_transparent: "assets/icon/app_icon_dark.png"
